#!/bin/sh
#

DEST_PREFIX=$HOME/opt/glint2

## ----- Where is your GALAHAD installation?
#GALAHAD_HOME=$HOME/opt/galahad
#GALAHAD_ARCH=mac64.osx.gfo
#export GALAHAD_INC_DIR="$GALAHAD_HOME/modules/$GALAHAD_ARCH/double"
#export GALAHAD_LIB_DIR="$GALAHAD_HOME/objects/$GALAHAD_ARCH/double"


# =========================================================
# The following prerequisites do not need to be touched, if they were
# installed via MacPorts.

# Which python we want to use --- whether it's the default, or some other
export PYTHON=/opt/local/bin/python

export EIGEN_DIR="/opt/local/include/eigen3"
export EIGEN_CFLAGS="-I $EIGEN_DIR"
export EIGEN_LIBS=""

#NETCDF_HOME=$HOME/opt/netcdf-4.1.3
NETCDF_HOME=/opt/local
export NETCDF_CFLAGS="-I $NETCDF_HOME/include"
export NETCDF_LIBS="-L$NETCDF_HOME/lib -lnetcdf"

NETCDFF_HOME=$HOME/opt/netcdf-fortran
export NETCDFF_CFLAGS="-I $NETCDFF_HOME/include"
export NETCDFF_LIBS="-L$NETCDFF_HOME/lib -lnetcdff"

MPI_HOME=$HOME/opt/openmpi-1.6.4
export MPI_INCLUDE="$MPI_HOME/include"
export MPI_CFLAGS="-I $MPI_INCLUDE"
export MPI_LIBS="-L$MPI_HOME/lib -lopenmpi"

export PROJ_HOME=/opt/local
export PROJ_CFLAGS="-I $PROJ_HOME/include"
export PROJ_LIBS="-L$PROJ_HOME/lib -lproj"

BLITZ_HOME=/opt/local
export BLITZ_CFLAGS="-I $BLITZ_HOME/include"
export BLITZ_LIBS="-L$BLITZ_HOME/lib -lblitz"


GMP_HOME=/opt/local
export GMP_CFLAGS="-I $GMP_HOME/include"
export GMP_LIBS="-L$GMP_HOME/lib -lgmp"

MPFR_HOME=/opt/local
export MPFR_CFLAGS="-I $MPFR_HOME/include"
export MPFR_LIBS="-L$MPFR_HOME/lib -lmpfr"

export CGAL_HOME=/opt/local

# ===================================================================
# Special rounding is required for CGAL
# -fp-model strict for intel
export CPPFLAGS="-frounding-math"


./configure --prefix=$DEST_PREFIX

