#!/bin/sh
#

DEST_PREFIX=$HOME_OPT/glint2

## ----- Where is your GALAHAD installation?
#GALAHAD_HOME=$HOME_OPT/galahad
#GALAHAD_ARCH=mac64.osx.gfo
#export GALAHAD_INC_DIR="$GALAHAD_HOME/modules/$GALAHAD_ARCH/double"
#export GALAHAD_LIB_DIR="$GALAHAD_HOME/objects/$GALAHAD_ARCH/double"


#export CC=gcc
#export CXX=g++


export CC=/usr/local/other/SLES11/gcc/4.7.1/bin/gcc
export CXX=/usr/local/other/SLES11/gcc/4.7.1/bin/g++

export FC="ifort"

# =========================================================
# The following prerequisites do not need to be touched, if they were
# installed via MacPorts.

# Which python we want to use --- whether it's the default, or some other
export PYTHON=/usr/bin/python

export BOOST_HOME=$HOME_OPT/boost-1.53.0

export EIGEN_CFLAGS="-I $HOME_OPT/eigen-3.1.3/include"
export EIGEN_LIBS=""

NETCDF_HOME=$HOME_OPT/netcdf-4.3.0
export NETCDF_CFLAGS="-I $NETCDF_HOME/include"
export NETCDF_LIBS="-L$NETCDF_HOME/lib -lnetcdf"

export NETCDFF_HOME=$HOME_OPT/netcdf-fortran-4.2
export NETCDFF_CFLAGS="-I$NETCDFF_HOME/include"
export NETCDFF_LIBS="""-L$NETCDFF_HOME/lib -lnetcdff"

export NETCDFCXX_HOME=$HOME_OPT/netcdf-cxx-4.2
export NETCDFCXX_CFLAGS="-I$NETCDFCXX_HOME/include"
export NETCDFCXX_LIBS="""-L$NETCDFCXX_HOME/lib -lnetcdf_c++"

#MPI_HOME=$HOME/opt/openmpi
export MPI_HOME=/usr/local/intel/mpi/3.2.2.006/lib64
export MPI_INCLUDE="$MPI_HOME/include"
export MPI_CFLAGS="-I $MPI_INCLUDE"
#export MPI_LIBS="-L$MPI_HOME/lib -lmpi -lmpi_cxx"
export MPI_LIBS="-L$MPI_HOME/lib -lmpi"
# Do I need -lmpiif or -lmpiic here????

export PROJ_HOME=$HOME_OPT/proj-4.8.0
export PROJ_CFLAGS="-I $PROJ_HOME/include"
export PROJ_LIBS="-L$PROJ_HOME/lib -lproj"

BLITZ_HOME=$HOME_OPT/blitz-0.10
export BLITZ_CFLAGS="-I $BLITZ_HOME/include"
export BLITZ_LIBS="-L$BLITZ_HOME/lib -lblitz"


#GMP_HOME=$HOME_OPT/gmp-5.1.1
#export GMP_CFLAGS="-I $GMP_HOME/include"
#export GMP_LIBS="-L$GMP_HOME/lib -lgmp"
#
#MPFR_HOME=$HOME_OPT/mpfr-3.1.2
#export MPFR_CFLAGS="-I $MPFR_HOME/include"
#export MPFR_LIBS="-L$MPFR_HOME/lib -lmpfr"

GMP_HOME=/usr
export GMP_CFLAGS="-I $GMP_HOME/include"
export GMP_LIBS="-L$GMP_HOME/lib64 -lgmp"

MPFR_HOME=/usr
export MPFR_CFLAGS="-I $MPFR_HOME/include"
export MPFR_LIBS="-L$MPFR_HOME/lib64 -lmpfr"


export CGAL_HOME=$HOME_OPT/cgal-4.0.2
export CGAL_CFLAGS="-I $CGAL_HOME/include"
export CGAL_LIBS="-L$CGAL_HOME/lib -lCGAL"

# Link fortran libraries into Python extension.  Other linking steps are
# done with the $(FCC), so this is not needed.
#export FORTRAN_LIBS="-lgfortran"

# ===================================================================
# Special rounding is required for CGAL
# -fp-model strict for intel
export CPPFLAGS="-frounding-math"
export AM_LDFLAGS="-Wl,-rpath=$CGAL_HOME/lib"	# cause it doesn't use libtool

./configure --prefix=$DEST_PREFIX --with-boost=$BOOST_HOME

