/* This file is machine-generated by cfextract.py.  DO NOT MODIFY!
Contents are derived from the file cf-standard-name-table.xml */

#include <giss/cfnames.hpp>

namespace giss {
namespace cf {

std::map<std::string, giss::CFName> const &standard_name_table()
{

static std::map<std::string, giss::CFName> ret {

{"land_ice_surface_specific_mass_balance_flux", {"land_ice_surface_specific_mass_balance_flux", "\"Land ice\" means glaciers, ice-caps and ice-sheets resting on bedrock and also includes ice-shelves. Specific mass balance means \
the net rate at which ice is added per unit area at the land ice surface. A negative value means loss of ice. In accordance with common \
usage in geophysical disciplines, \"flux\" implies per unit area, called \"flux density\" in physics.", "kg m-2 s-1", "", ""}},

{"surface_downward_latent_heat_flux", {"surface_downward_latent_heat_flux", "The surface called \"surface\" means the lower boundary of the atmosphere. \"Downward\" indicates a vector component which is positive \
when directed downward (negative upward). The surface latent heat flux is the exchange of heat between the surface and the air on \
account of evaporation (including sublimation). In accordance with common usage in geophysical disciplines, \"flux\" implies per unit \
area, called \"flux density\" in physics.", "W m-2", "", ""}},

{"surface_downward_sensible_heat_flux", {"surface_downward_sensible_heat_flux", "The surface called \"surface\" means the lower boundary of the atmosphere. \"Downward\" indicates a vector component which is positive \
when directed downward (negative upward). The surface sensible heat flux, also called \"turbulent\" heat flux, is the exchange of \
heat between the surface and the air by motion of air. In accordance with common usage in geophysical disciplines, \"flux\" implies \
per unit area, called \"flux density\" in physics.", "W m-2", "", ""}},

{"surface_temperature", {"surface_temperature", "The surface called \"surface\" means the lower boundary of the atmosphere. The surface temperature is the temperature at the interface, \
not the bulk temperature of the medium above or below. Unless indicated in the cell_methods attribute, a quantity is assumed to apply \
to the whole area of each horizontal grid box. Previously, the qualifier where_type was used to specify that the quantity applies \
only to the part of the grid box of the named type.  Names containing the where_type qualifier are deprecated and newly created data \
should use the cell_methods attribute to indicate the horizontal area to which the quantity applies.", "K", "E139", ""}},

};
return ret;
}

}} // namespace
