# Input Variables
#    GTEST_ROOT
# Produces:
#    GTEST_LIBRARY
#    GTEST_INCLUDE_DIR


FIND_PATH(GTEST_INCLUDE_DIR gtest
	HINTS ${GTEST_ROOT}/include)

FIND_LIBRARY(GTEST_LIBRARY_MAIN NAMES gtest
	HINTS ${GTEST_ROOT}/lib)

list(APPEND GTEST_LIBRARY ${GTEST_LIBRARY_MAIN} -lpthread -lm)

IF (GTEST_INCLUDE_DIR AND GTEST_LIBRARY)
   SET(GTEST_FOUND TRUE)
ENDIF (GTEST_INCLUDE_DIR AND GTEST_LIBRARY)

IF (GTEST_FOUND)
   IF (NOT GTEST_FIND_QUIETLY)
      MESSAGE(STATUS "Found  xxx GTEST_LIBRARY: ${GTEST_LIBRARY}")
      MESSAGE(STATUS "Found  xxx GTEST_INCLUDE_DIR: ${GTEST_INCLUDE_DIR}")
   ENDIF (NOT GTEST_FIND_QUIETLY)
ELSE (GTEST_FOUND)
   IF (GTEST_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find GTEST")
   ENDIF (GTEST_FIND_REQUIRED)
ENDIF (GTEST_FOUND)
