# Input Variables
#    NETCDF_FORTRAN_ROOT
# Produces:
#    NETCDF_FORTRAN_LIBRARY
#    NETCDF_FORTRAN_INCLUDE_DIR


FIND_PATH(NETCDF_FORTRAN_INCLUDE_DIR netcdf.mod
	HINTS ${NETCDF_FORTRAN_ROOT}/include)

FIND_LIBRARY(NETCDF_FORTRAN_LIBRARY NAMES netcdff
	HINTS ${NETCDF_FORTRAN_ROOT}/lib)

IF (NETCDF_FORTRAN_INCLUDE_DIR AND NETCDF_FORTRAN_LIBRARY)
   SET(NETCDF_FORTRAN_FOUND TRUE)
ENDIF (NETCDF_FORTRAN_INCLUDE_DIR AND NETCDF_FORTRAN_LIBRARY)

IF (NETCDF_FORTRAN_FOUND)
   IF (NOT NETCDF_FORTRAN_FIND_QUIETLY)
      MESSAGE(STATUS "Found NETCDF_FORTRAN_LIBRARY: ${NETCDF_FORTRAN_LIBRARY}")
   ENDIF (NOT NETCDF_FORTRAN_FIND_QUIETLY)
ELSE (NETCDF_FORTRAN_FOUND)
   IF (NETCDF_FORTRAN_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find NETCDF_FORTRAN")
   ENDIF (NETCDF_FORTRAN_FIND_REQUIRED)
ENDIF (NETCDF_FORTRAN_FOUND)
