# Input Variables
#    SPSPARSE_ROOT
# Produces:
#    SPSPARSE_LIBRARY
#    SPSPARSE_INCLUDE_DIR


FIND_PATH(SPSPARSE_INCLUDE_DIR spsparse/array.hpp
	HINTS ${SPSPARSE_ROOT}/include)

FIND_LIBRARY(SPSPARSE_LIBRARY NAMES spsparse
	HINTS ${SPSPARSE_ROOT}/lib)

IF (SPSPARSE_INCLUDE_DIR AND SPSPARSE_LIBRARY)
   SET(SPSPARSE_FOUND TRUE)
ENDIF (SPSPARSE_INCLUDE_DIR AND SPSPARSE_LIBRARY)

IF (SPSPARSE_FOUND)
   IF (NOT SPSPARSE_FIND_QUIETLY)
      MESSAGE(STATUS "Found SPSPARSE_LIBRARY: ${SPSPARSE_LIBRARY}")
   ENDIF (NOT SPSPARSE_FIND_QUIETLY)
ELSE (SPSPARSE_FOUND)
   IF (SPSPARSE_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find SPSPARSE")
   ENDIF (SPSPARSE_FIND_REQUIRED)
ENDIF (SPSPARSE_FOUND)
