# Input Variables
#    NETCDF4_CXX_ROOT
# Produces:
#    NETCDF4_CXX_LIBRARY
#    NETCDF4_CXX_INCLUDE_DIR


FIND_PATH(NETCDF4_CXX_INCLUDE_DIR netcdf
	HINTS ${NETCDF4_CXX_ROOT}/include)

FIND_LIBRARY(NETCDF4_CXX_LIBRARY NAMES netcdf-cxx4
	HINTS ${NETCDF4_CXX_ROOT}/lib ${NETCDF4_CXX_ROOT}/lib64)


IF (NETCDF4_CXX_INCLUDE_DIR AND NETCDF4_CXX_LIBRARY)
   SET(NETCDF4_CXX_FOUND TRUE)
ENDIF (NETCDF4_CXX_INCLUDE_DIR AND NETCDF4_CXX_LIBRARY)

IF (NETCDF4_CXX_FOUND)
   IF (NOT NETCDF4_CXX_FIND_QUIETLY)
      MESSAGE(STATUS "Found NETCDF4_CXX_LIBRARY: ${NETCDF4_CXX_LIBRARY}")
   ENDIF (NOT NETCDF4_CXX_FIND_QUIETLY)
ELSE (NETCDF4_CXX_FOUND)
   IF (NETCDF4_CXX_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find NETCDF4_CXX")
   ENDIF (NETCDF4_CXX_FIND_REQUIRED)
ENDIF (NETCDF4_CXX_FOUND)
