# Input Variables
#    GALAHAD_ROOT
# Produces:
#    GALAHAD_LIBRARIES
#    GALAHAD_INCLUDE_DIRS


FIND_PATH(GALAHAD_INCLUDE_DIRS galahad_symbols.mod
	HINTS ${GALAHAD_ROOT}/include)


set(GALAHAD_LIB_DIR ${GALAHAD_ROOT}/lib)
set(GALAHAD_COMPONENTS galahad galahad_hsl galahad_pardiso galahad_wsmp galahad_metis galahad_lapack galahad_blas galahad_spral)
set(GALAHAD_LIBRARIES )                # Part of GCC
foreach(COMPONENT ${GALAHAD_COMPONENTS})
    string(TOUPPER ${COMPONENT} UPPERCOMPONENT)
    find_library(${UPPERCOMPONENT}_LIBRARY ${COMPONENT} HINTS ${GALAHAD_LIB})
       message(adding ${UPPERCOMPONENT} --- ${${UPPERCOMPONENT}_LIBRARY})
       list(APPEND GALAHAD_LIBRARIES ${${UPPERCOMPONENT}_LIBRARY})
endforeach()



#FIND_LIBRARY(GALAHAD_LIBRARIES NAMES galahad
#	HINTS ${GALAHAD_ROOT}/lib)

IF (GALAHAD_INCLUDE_DIRS AND GALAHAD_LIBRARIES)
   SET(GALAHAD_FOUND TRUE)
ENDIF (GALAHAD_INCLUDE_DIRS AND GALAHAD_LIBRARIES)

IF (GALAHAD_FOUND)
   IF (NOT GALAHAD_FIND_QUIETLY)
      MESSAGE(STATUS "Found GALAHAD_LIBRARIES: ${GALAHAD_LIBRARIES}")
   ENDIF (NOT GALAHAD_FIND_QUIETLY)
ELSE (GALAHAD_FOUND)
   IF (GALAHAD_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find GALAHAD")
   ENDIF (GALAHAD_FIND_REQUIRED)
ENDIF (GALAHAD_FOUND)
