# Input Variables
#    EVERYTRACE_ROOT
# Produces:
#    EVERYTRACE_LIBRARY
#    EVERYTRACE_INCLUDE_DIR


FIND_PATH(EVERYTRACE_INCLUDE_DIR everytrace.h
	HINTS ${EVERYTRACE_ROOT}/include)

FIND_LIBRARY(EVERYTRACE_C_LIBRARY NAMES everytrace_c
	HINTS ${EVERYTRACE_ROOT}/lib)
FIND_LIBRARY(EVERYTRACE_CF_LIBRARY NAMES everytrace_cf
	HINTS ${EVERYTRACE_ROOT}/lib)
FIND_LIBRARY(EVERYTRACE_C_MPI_LIBRARY NAMES everytrace_c_mpi
	HINTS ${EVERYTRACE_ROOT}/lib)
FIND_LIBRARY(EVERYTRACE_CF_MPI_LIBRARY NAMES everytrace_cf_mpi
	HINTS ${EVERYTRACE_ROOT}/lib)

FIND_FILE(EVERYTRACE_REFADDR NAMES everytrace_refaddr.o
	HINTS ${EVERYTRACE_ROOT}/lib)



IF (EVERYTRACE_C_INCLUDE_DIR AND EVERYTRACE_C_LIBRARY)
   SET(EVERYTRACE_C_FOUND TRUE)
endif()

IF (EVERYTRACE_C_INCLUDE_DIR AND EVERYTRACE_F_INCLUDE_DIR AND EVERYTRACE_CF_LIBRARY)
   SET(EVERYTRACE_CF_FOUND TRUE)
endif()

IF (EVERYTRACE_C_INCLUDE_DIR AND EVERYTRACE_C_MPI_LIBRARY)
   SET(EVERYTRACE_C_MPI_FOUND TRUE)
endif()

IF (EVERYTRACE_C_INCLUDE_DIR AND EVERYTRACE_F_INCLUDE_DIR AND EVERYTRACE_CF_MPI_LIBRARY)
   SET(EVERYTRACE_CF_MPI_FOUND TRUE)
endif()


IF (EVERYTRACE_C_FOUND)
   IF (NOT EVERYTRACE_FIND_QUIETLY)
      MESSAGE(STATUS "Found EVERYTRACE_C_LIBRARY: ${EVERYTRACE_C_LIBRARY}")
   ENDIF (NOT EVERYTRACE_FIND_QUIETLY)
ELSE (EVERYTRACE_C_FOUND)
   IF (EVERYTRACE_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find EVERYTRACE")
   ENDIF (EVERYTRACE_FIND_REQUIRED)
ENDIF(EVERYTRACE_C_FOUND)
