# Input Variables
#    NETCDF4_C_ROOT
# Produces:
#    NETCDF4_C_LIBRARY
#    NETCDF4_C_INCLUDE_DIR


FIND_PATH(NETCDF4_C_INCLUDE_DIR netcdf.h
	HINTS ${NETCDF4_C_ROOT}/include)

FIND_LIBRARY(NETCDF4_C_LIBRARY NAMES netcdf
	HINTS ${NETCDF4_C_ROOT}/lib)

IF (NETCDF4_C_INCLUDE_DIR AND NETCDF4_C_LIBRARY)
   SET(NETCDF4_C_FOUND TRUE)
ENDIF (NETCDF4_C_INCLUDE_DIR AND NETCDF4_C_LIBRARY)

IF (NETCDF4_C_FOUND)
   IF (NOT NETCDF4_C_FIND_QUIETLY)
      MESSAGE(STATUS "Found NETCDF4_C_LIBRARY: ${NETCDF4_C_LIBRARY}")
   ENDIF (NOT NETCDF4_C_FIND_QUIETLY)
ELSE (NETCDF4_C_FOUND)
   IF (NETCDF4_C_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find NETCDF4_C")
   ENDIF (NETCDF4_C_FIND_REQUIRED)
ENDIF (NETCDF4_C_FOUND)
