# Input Variables
#    NETCDF4_FORTRAN_ROOT
# Produces:
#    NETCDF4_FORTRAN_LIBRARY
#    NETCDF4_FORTRAN_INCLUDE_DIR


FIND_PATH(NETCDF4_FORTRAN_INCLUDE_DIR netcdf.mod
	HINTS ${NETCDF4_FORTRAN_ROOT}/include)

FIND_LIBRARY(NETCDF4_FORTRAN_LIBRARY NAMES netcdff
	HINTS ${NETCDF4_FORTRAN_ROOT}/lib)

IF (NETCDF4_FORTRAN_INCLUDE_DIR AND NETCDF4_FORTRAN_LIBRARY)
   SET(NETCDF4_FORTRAN_FOUND TRUE)
ENDIF (NETCDF4_FORTRAN_INCLUDE_DIR AND NETCDF4_FORTRAN_LIBRARY)

IF (NETCDF4_FORTRAN_FOUND)
   IF (NOT NETCDF4_FORTRAN_FIND_QUIETLY)
      MESSAGE(STATUS "Found NETCDF4_FORTRAN_LIBRARY: ${NETCDF4_FORTRAN_LIBRARY}")
   ENDIF (NOT NETCDF4_FORTRAN_FIND_QUIETLY)
ELSE (NETCDF4_FORTRAN_FOUND)
   IF (NETCDF4_FORTRAN_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find NETCDF4_FORTRAN")
   ENDIF (NETCDF4_FORTRAN_FIND_REQUIRED)
ENDIF (NETCDF4_FORTRAN_FOUND)
