# Input Variables
#    IBMISC_ROOT
# Produces:
#    IBMISC_LIBRARY
#    IBMISC_INCLUDE_DIR


FIND_PATH(IBMISC_INCLUDE_DIR ibmisc
	HINTS ${IBMISC_ROOT}/include)

FIND_LIBRARY(IBMISC_LIBRARY NAMES ibmisc
	HINTS ${IBMISC_ROOT}/lib)

IF (IBMISC_INCLUDE_DIR AND IBMISC_LIBRARY)
   SET(IBMISC_FOUND TRUE)
ENDIF (IBMISC_INCLUDE_DIR AND IBMISC_LIBRARY)

IF (IBMISC_FOUND)
   IF (NOT IBMISC_FIND_QUIETLY)
      MESSAGE(STATUS "Found  xxx IBMISC_LIBRARY: ${IBMISC_LIBRARY}")
      MESSAGE(STATUS "Found  xxx IBMISC_INCLUDE_DIR: ${IBMISC_INCLUDE_DIR}")
   ENDIF (NOT IBMISC_FIND_QUIETLY)
ELSE (IBMISC_FOUND)
   IF (IBMISC_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find IBMISC")
   ENDIF (IBMISC_FIND_REQUIRED)
ENDIF (IBMISC_FOUND)
