# Input Variables
#    NETCDF_CXX_ROOT
# Produces:
#    NETCDF_CXX_LIBRARY
#    NETCDF_CXX_INCLUDE_DIR


FIND_PATH(NETCDF_CXX_INCLUDE_DIR netcdfcpp.h
	HINTS ${NETCDF_CXX_ROOT}/include)

FIND_LIBRARY(NETCDF_CXX_LIBRARY NAMES netcdf_c++
	HINTS ${NETCDF_CXX_ROOT}/lib ${NETCDF_CXX_ROOT}/lib64)


IF (NETCDF_CXX_INCLUDE_DIR AND NETCDF_CXX_LIBRARY)
   SET(NETCDF_CXX_FOUND TRUE)
ENDIF (NETCDF_CXX_INCLUDE_DIR AND NETCDF_CXX_LIBRARY)

IF (NETCDF_CXX_FOUND)
   IF (NOT NETCDF_CXX_FIND_QUIETLY)
      MESSAGE(STATUS "Found NETCDF_CXX_LIBRARY: ${NETCDF_CXX_LIBRARY}")
   ENDIF (NOT NETCDF_CXX_FIND_QUIETLY)
ELSE (NETCDF_CXX_FOUND)
   IF (NETCDF_CXX_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find NETCDF_CXX")
   ENDIF (NETCDF_CXX_FIND_REQUIRED)
ENDIF (NETCDF_CXX_FOUND)
