# Input Variables
#    BLITZ_ROOT
# Produces:
#    BLITZ_LIBRARY
#    BLITZ_INCLUDE_DIR


FIND_PATH(BLITZ_INCLUDE_DIR blitz/array.h
	HINTS ${BLITZ_ROOT}/include)

FIND_LIBRARY(BLITZ_LIBRARY NAMES blitz
	HINTS ${BLITZ_ROOT}/lib)

IF (BLITZ_INCLUDE_DIR AND BLITZ_LIBRARY)
   SET(BLITZ_FOUND TRUE)
ENDIF (BLITZ_INCLUDE_DIR AND BLITZ_LIBRARY)

IF (BLITZ_FOUND)
   IF (NOT BLITZ_FIND_QUIETLY)
      MESSAGE(STATUS "Found BLITZ_LIBRARY: ${BLITZ_LIBRARY}")
   ENDIF (NOT BLITZ_FIND_QUIETLY)
ELSE (BLITZ_FOUND)
   IF (BLITZ_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find BLITZ")
   ENDIF (BLITZ_FIND_REQUIRED)
ENDIF (BLITZ_FOUND)
